### ISSUE TITLE
Seeking Clarity on Which Cluster Management LIF?

### ISSUE THREAD

**Issue by TheAuthority** [NetAppDocs/ontap-automation#49]
Page: [How to access the ONTAP REST API](https://docs.netapp.com/us-en/ontap-automation/rest/access_rest_api.html)

> You should always use the cluster management LIF.

_THE_ cluster management LIF (which I think is called "cluster_mgmt" by default) or _ANY_ cluster management LIF?

We create specific-use cluster-mgmt LIFs for different purposes.  I have assumed they always worked identically, but it wouldn't be the first time I've seen preference given to a built-in thing over a created thing.

**Comment by dmp-netapp** [comment]
Thanks for your feedback. We are reviewing now.

**Comment by dmp-netapp** [comment]
I have consulted with ONTAP engineering and expect to provide more detail soon.

**Comment by dmp-netapp** [comment]
I have updated the documentation page cited at top ("How to access the ONTAP REST API"). The change is live. Closing this issue.
